### ISSUE TITLE
Version 1.3.1 TwigCacheExtension not compatible

### ISSUE THREAD

**Issue by Gemineye** [EmanueleMinotto/TwigCacheBundle#17]
Hi,

I think this change breaks your logic in the dependency injection:

https://github.com/asm89/twig-cache-extension/commit/0ffaf529de8662eb0bccae00c9075871ac256839

You also need to check the Twig version I think.

Regards Harald

**Comment by EmanueleMinotto** [comment]
Thank you, I'll check asap

**Comment by rvanlaak** [comment]
Same here, the Twig extension isn't enabled anymore on build. Probably not related, but we also updated to Twig 1.30 at the same time. Also see https://github.com/asm89/twig-cache-extension/issues/40

**Comment by DenysMedvid** [comment]
I think, there is solution in PR  #16

**Comment by krafas** [comment]
@EmanueleMinotto did you check? :)

**Comment by Gemineye** [comment]
Any news?

**Comment by buffcode** [comment]
I fixed a similar issue using a custom service, see here for reference:
https://github.com/asm89/twig-cache-extension/pull/46#issuecomment-276946354

**Comment by EmanueleMinotto** [comment]
This is solved in [v1.0.4](https://github.com/EmanueleMinotto/TwigCacheBundle/releases/tag/1.0.4)
